### PR TITLE
Replaced 'winston-logfmt' by 'winston' package.

### LINKED ISSUE #2: If an error occurs the pod gets OOMkilled
Example:
```
---
apiVersion: bunny-cdn-operator.com/v1alpha1
kind: PullZone
metadata:
  name: test.something.else # => This is wrong
  namespace: default
spec:
  originUrl: https://google.com
  deletionPolicy: delete
```

The problem is caused by the logger from the `winston-logfmt` going into an endless loop.

### PR DESCRIPTION
**Pull request by jeroenvermeulen**
Fixes #2

### CODE REVIEW

**Review by paulrostorp — CHANGES_REQUESTED** [review]
It's an important requirement to maintain structured logging.
I don't have the bandwidth to fix the logfmt implementation atm, but maybe you could enable the Winston builtin json logger ?

**Comment by jeroenvermeulen** [comment]
@paulrostorp With the `winston` package it logs like this:
```
debug: Starting Bunny CDN Operator...
info: watching resource edgerules.bunny-cdn-operator.com/v1alpha1
info: watching resource storagezones.bunny-cdn-operator.com/v1alpha1
info: watching resource pullzones.bunny-cdn-operator.com/v1alpha1
debug: Bunny CDN Operator started.
debug: Processing change to Pull Zone local-app-cloud...
```
Isn't that structured enough?

**Comment by paulrostorp** [comment]
> @paulrostorp With the `winston` package it logs like this:
> 
> ```
> debug: Starting Bunny CDN Operator...
> info: watching resource edgerules.bunny-cdn-operator.com/v1alpha1
> info: watching resource storagezones.bunny-cdn-operator.com/v1alpha1
> info: watching resource pullzones.bunny-cdn-operator.com/v1alpha1
> debug: Bunny CDN Operator started.
> debug: Processing change to Pull Zone local-app-cloud...
> ```
> 
> Isn't that structured enough?


@jeroenvermeulen That isn't a structure log management tools support by default and can index+search easily. Most log management tools have built-in support logfmt and json logs, including Grafana Loki which I use.

Winston's JSON logger will suffice: https://github.com/winstonjs/winston#usage

**Comment by jeroenvermeulen** [comment]
@paulrostorp Updated PR. Now it logs like this:
```
{"level":"debug","message":"Starting Bunny CDN Operator..."}
{"level":"info","message":"watching resource edgerules.bunny-cdn-operator.com/v1alpha1"}
{"level":"info","message":"watching resource storagezones.bunny-cdn-operator.com/v1alpha1"}
{"level":"info","message":"watching resource pullzones.bunny-cdn-operator.com/v1alpha1"}
{"level":"debug","message":"Bunny CDN Operator started."}
{"level":"debug","message":"Processing change to Pull Zone local-app-cloud..."}
```

**Review by paulrostorp — APPROVED** [review]

**Pull request merged**
